version: "3.9"

networks:
  red-proyecto:
    external: true   # usa la red ya creada arriba

services:

  # ── SERVIDOR PRINCIPAL ──────────────────────────────────────────
  servidor:
    build:
      context: ./servidor
      dockerfile: Dockerfile
    container_name: srv-redes
    hostname: servidor
    networks:
      red-proyecto:
        ipv4_address: 172.20.0.10   # ← IP fija propia (no localhost)
    ports:
      - "2222:22"   # SSH expuesto al host
      - "8080:80"   # Web (Apache/Nginx)
    volumes:
      - vol-datos:/datos
      - vol-respaldos:/respaldos
      - ./logs:/var/log/proyecto
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN   # necesario para cuotas y montajes internos

  # ── CLIENTE ─────────────────────────────────────────────────────
  cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    container_name: cli-redes
    hostname: cliente
    networks:
      red-proyecto:
        ipv4_address: 172.20.0.20
    depends_on:
      - servidor
    restart: unless-stopped

  # ── MONITOR (Prometheus + Grafana) ──────────────────────────────
