[supervisord]
nodaemon=true
logfile=/var/log/proyecto/supervisord.log

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/proyecto/sshd.log

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/proyecto/apache2.log

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=/var/log/proyecto/cron.log

[program:syslog-ng]
command=syslog-ng -F
autostart=true
autorestart=true
stdout_logfile=/var/log/proyecto/syslog.log